---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploybot-sa
  namespace: demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: demo
  name: deploybot-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploybot-binding
  namespace: demo
subjects:
- kind: ServiceAccount
  name: deploybot-sa
  namespace: demo
roleRef:
  kind: Role
  name: deploybot-role
  apiGroup: rbac.authorization.k8s.io