
apiVersion: v1
kind: Service
metadata:
  name: loadlab-service
  namespace: demo
spec:
  selector:
    app: loadlab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
